export type EVVehicle = {
  id: string;
  external_id: number;
  slug: string;
  source_url: string;
  data_source: string;
  availability: string | null;
  make: string;
  model: string;
  variant: string | null;
  full_name: string;
  image_url: string | null;
  image_urls?: string[] | null;
  price_eur: number | null;
  lease_price_eur_month: number | null;
  battery_usable_kwh: number | null;
  battery_nominal_kwh: number | null;
  range_real_km: number | null;
  efficiency_wh_per_km: number | null;
  wltp_range_km: number | null;
  acceleration_0_100_s: number | null;
  top_speed_kmh: number | null;
  drive: string | null;
  seats: number | null;
  fastcharge_speed_avg_kw: number | null;
  fastcharge_speed_kmh: number | null;
  charge_power_ac_kw: number | null;
  charge_time_ac: string | null;
  plug_type: string | null;
  curb_weight_kg: number | null;
  gross_weight_kg: number | null;
  towing_weight_braked_kg: number | null;
  towing_weight_unbraked_kg: number | null;
  towbar_possible: boolean | null;
  roof_load_kg: number | null;
  boot_space_liters: number | null;
  boot_space_max_liters: number | null;
  v2l_supported: boolean | null;
  body_type: string | null;
  segment: string | null;
  raw_specs: Record<string, string | number | boolean | null>;
  last_scraped_at: string;
  created_at: string;
  updated_at: string;
};
